name: Build & Release

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  publish:
    name: Publish 
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    # Setting up Node
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: '12.16.1'
    
    # Installing Dependencies
    - name: Installing Dependencies
      run: yarn install
    - name: Build
      run: yarn tauri build
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: target/release/app
        asset_name: app
        tag: ${{ github.ref }}