name: Build & Release

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  publish:
    name: Publish for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: mysql-syncer
            asset_name: mysql-sync-linux
          - os: windows-latest
            artifact_name: mysql-syncer.exe
            asset_name: sql-sync-windows.exe
          - os: macos-latest
            artifact_name: mysql-syncer
            asset_name: mysql-sync-macos

    steps:
    - uses: actions/checkout@v2
    # Setting up Node
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: '12.16.1'
    
    # Installing Dependencies
    - name: Installing Dependencies
      run: npm ci
    - name: Build
      run: cargo build --release --locked
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: target/release/${{ matrix.artifact_name }}
        asset_name: ${{ matrix.asset_name }}
        tag: ${{ github.ref }}